<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://relaxng.org/ns/structure/1.0"?>
<package format="3">
  <name>esp32s3_node</name>
  <version>1.0.0</version>
  <description>Driver serial MiniPC -&gt; ESP32-S3 (USB-OTG), khong phu thuoc rclcpp.</description>
  <maintainer email="pmd0793724602@gmail.com">Pham Minh Duc</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>