<?xml version="1.0"?>
<package format="3">
  <name>gui_matplotlib</name>
  <version>0.1.0</version>
  <description>Python + Matplotlib dashboard for lane detection (white theme, polar LIDAR map)</description>
  <maintainer email="duc@todo.todo">Pham Minh Duc</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>python3-matplotlib</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
