<?xml version="1.0"?>
<package format="3">
  <name>traffic_light_detector</name>
  <version>0.1.0</version>
  <description>NCNN traffic-light and sign detector for ROS 2.</description>
  <maintainer email="duc@todo.todo">Duc Pham</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
